/* ============================================================================
   locations.js  —  ALL your map data lives here.
   (Regenerated by Edit Mode. Edit by hand or use ?edit=1 and Export again.)
   x / y are percentages 0-100 across the map image.
   ========================================================================== */

window.MARKER_TYPES = {
  restrooms: { icon: "🚻", label: "Restrooms" },
  food: { icon: "🍔", label: "Food & Drinks" },
  cornhole: { icon: "🌽", label: "Cornhole" },
  horseshoes: { icon: "🧲", label: "Horseshoes" },
  volleyball: { icon: "🏐", label: "Volleyball" },
  bounce_house: { icon: "🏰", label: "Bounce House" },
  bucket_golf: { icon: "⛳", label: "Bucket Golf" },
  chess: { icon: "♟️", label: "Chess" },
  checkers: { icon: "⚫", label: "Checkers" },
  giant_bubbles: { icon: "🫧", label: "Giant Bubbles" },
  small_kids: { icon: "🧸", label: "Small Kids Area" },
  photo_booth: { icon: "📸", label: "Photo Booth" },
  first_aid: { icon: "⛑️", label: "First Aid" },
  ladder_ball: { icon: "🪜", label: "Ladder Ball" },
  washer_toss: { icon: "🥏", label: "Washer Toss" },
  spike_ball: { icon: "🔵", label: "Spike Ball" },
  pickleball: { icon: "🥒", label: "Pickleball" },
  football: { icon: "🏈", label: "Football" },
  croquet: { icon: "🏑", label: "Croquet" },
  bocce_ball: { icon: "🟤", label: "Bocce Ball" },
  giant_jenga: { icon: "🧱", label: "Giant Jenga" },
  can_jam: { icon: "🥫", label: "Can Jam" },
  slip_slide: { icon: "🛝", label: "Slip and Slide" },
  the_island: { icon: "🏝️", label: "The Island" },
  tournament_signup: { icon: "📋", label: "Tournament Sign-Up" }
};

window.MARKERS = [
  { id: "restrooms-1", type: "restrooms", x: 78, y: 54.1, name: "Restrooms", description: "By the food lines downstairs, and upstairs near the east entrance. Family bathroom available." },
  { id: "cornhole-1", type: "cornhole", x: 22.9, y: 28.9, name: "Cornhole", description: "4 sets. Make sure to sign up for the tournament.", time: "1:30 PM" },
  { id: "horseshoes-1", type: "horseshoes", x: 50.9, y: 17.6, name: "Horseshoes", description: "2 sets. Don't forget to sign up for the tournament.", time: "2:15 PM" },
  { id: "volleyball-1", type: "volleyball", x: 21.6, y: 42.5, name: "Volleyball", description: "2 courts. Make sure to sign up for the tournament.", time: "3:00 PM" },
  { id: "bounce_house-1", type: "bounce_house", x: 36.5, y: 49.1, name: "Bounce House", description: "2 bounce houses." },
  { id: "bucket_golf-1", type: "bucket_golf", x: 55.5, y: 52.9, name: "Bucket Golf", description: "Grab a ball and a club. All holes are par 3, and you subtract a stroke if you make it in the bucket." },
  { id: "chess-1", type: "chess", x: 36.9, y: 38.1, name: "Chess", description: "2 sets of chess." },
  { id: "checkers-1", type: "checkers", x: 36.9, y: 43.6, name: "Checkers", description: "2 sets of checkers." },
  { id: "giant_bubbles-1", type: "giant_bubbles", x: 62.2, y: 51.6, name: "Giant Bubbles", description: "Make 20-foot-long bubbles with this awesome mixture." },
  { id: "small_kids-1", type: "small_kids", x: 65.8, y: 45.2, name: "Kids Area", description: "Kids' horseshoes, ring toss, and giant Connect Four." },
  { id: "photo_booth-1", type: "photo_booth", x: 67.7, y: 34, name: "Photo Booth", description: "2 styles of photo booth pictures." },
  { id: "first_aid-1", type: "first_aid", x: 70.3, y: 56, name: "First Aid", description: "First aid is available upon request." },
  { id: "ladder_ball-1", type: "ladder_ball", x: 45.2, y: 52, name: "Ladder Ball", description: "" },
  { id: "washer_toss-1", type: "washer_toss", x: 22.9, y: 20, name: "Washer Toss", description: "" },
  { id: "spike_ball-1", type: "spike_ball", x: 75.2, y: 24.8, name: "Spike Ball", description: "A hard game made for the athlete." },
  { id: "pickleball-1", type: "pickleball", x: 47.5, y: 22.7, name: "Pickleball", description: "No lines are sprayed." },
  { id: "football-1", type: "football", x: 9.7, y: 38.7, name: "Football", description: "Field with a goal post." },
  { id: "croquet-1", type: "croquet", x: 66.3, y: 39.5, name: "Croquet", description: "" },
  { id: "bocce_ball-1", type: "bocce_ball", x: 68, y: 24.2, name: "Bocce Ball", description: "A regulation court setup for play." },
  { id: "giant_jenga-1", type: "giant_jenga", x: 66.7, y: 50.2, name: "Giant Jenga", description: "Test your hand at this giant challenge." },
  { id: "can_jam-1", type: "can_jam", x: 66.1, y: 28.9, name: "Can Jam", description: "" },
  { id: "slip_slide-1", type: "slip_slide", x: 36.6, y: 56.1, name: "Slip and Slide", description: "2 slip and slides with a hose leading into the pond." },
  { id: "the_island-1", type: "the_island", x: 33.9, y: 65, name: "The Island", description: "A large floating island to play on in the pond." },
  { id: "restrooms-mr6q9kvr166", type: "restrooms", x: 74.5, y: 35.8, name: "Restrooms", description: "In the back hallway downstairs. Family bathroom available." },
  { id: "tournament_signup-1", type: "tournament_signup", x: 74.7, y: 53, name: "Tournament Sign-Up", description: "Sign up here for the tournaments: Cornhole (1:30 PM), Horseshoes (2:15 PM), and Volleyball (3:00 PM)." }
];
