/* ============================================================================
   locations.js  —  ALL your map data lives here.
   (Regenerated by Edit Mode. Edit by hand or use ?edit=1 and Export again.)
   x / y are percentages 0-100 across the map image.
   ========================================================================== */

window.MARKER_TYPES = {
  restrooms: { icon: "🚻", label: "Restrooms" },
  food: { icon: "🍔", label: "Food & Drinks" },
  cornhole: { icon: "🌽", label: "Cornhole" },
  horseshoes: { icon: "🧲", label: "Horseshoes" },
  volleyball: { icon: "🏐", label: "Volleyball" },
  bounce_house: { icon: "🏰", label: "Bounce House" },
  bucket_golf: { icon: "⛳", label: "Bucket Golf" },
  chess: { icon: "♟️", label: "Chess" },
  checkers: { icon: "⚫", label: "Checkers" },
  giant_bubbles: { icon: "🫧", label: "Giant Bubbles" },
  small_kids: { icon: "🧸", label: "Small Kids Area" },
  photo_booth: { icon: "📸", label: "Photo Booth" },
  first_aid: { icon: "⛑️", label: "First Aid" },
  ladder_ball: { icon: "🪜", label: "Ladder Ball" },
  washer_toss: { icon: "🥏", label: "Washer Toss" },
  spike_ball: { icon: "🔵", label: "Spike Ball" },
  pickleball: { icon: "🥒", label: "Pickleball" },
  football: { icon: "🏈", label: "Football" },
  croquet: { icon: "🏑", label: "Croquet" },
  bocce_ball: { icon: "🟤", label: "Bocce Ball" },
  giant_jenga: { icon: "🧱", label: "Giant Jenga" },
  can_jam: { icon: "🥫", label: "Can Jam" },
  slip_slide: { icon: "🛝", label: "Slip and Slide" },
  the_island: { icon: "🏝️", label: "The Island" }
};

window.MARKERS = [
  { id: "restrooms-1", type: "restrooms", x: 76.7, y: 53, name: "Restrooms", description: "By the food lines" },
  { id: "cornhole-1", type: "cornhole", x: 22.9, y: 28.9, name: "Cornhole", description: "4 sets", time: "1:30 PM" },
  { id: "horseshoes-1", type: "horseshoes", x: 49.4, y: 18.8, name: "Horseshoes", description: "", time: "2:15 PM" },
  { id: "volleyball-1", type: "volleyball", x: 21.6, y: 42.5, name: "Volleyball", description: "2 courts", time: "3:00 PM" },
  { id: "bounce_house-1", type: "bounce_house", x: 36.5, y: 49.1, name: "Bounce House", description: "2 Bounce houses" },
  { id: "bucket_golf-1", type: "bucket_golf", x: 54.7, y: 52.4, name: "Bucket Golf", description: "Starts here" },
  { id: "chess-1", type: "chess", x: 37, y: 39.4, name: "Chess", description: "" },
  { id: "checkers-1", type: "checkers", x: 36.9, y: 43.6, name: "Checkers", description: "" },
  { id: "giant_bubbles-1", type: "giant_bubbles", x: 62.2, y: 51.6, name: "Giant Bubbles", description: "" },
  { id: "small_kids-1", type: "small_kids", x: 65.4, y: 47, name: "Kids Area", description: "" },
  { id: "photo_booth-1", type: "photo_booth", x: 36.9, y: 35.5, name: "Photo Booth", description: "" },
  { id: "first_aid-1", type: "first_aid", x: 70.3, y: 56, name: "First Aid", description: "First aid station." },
  { id: "ladder_ball-1", type: "ladder_ball", x: 45.2, y: 52, name: "Ladder Ball", description: "" },
  { id: "washer_toss-1", type: "washer_toss", x: 22.9, y: 20, name: "Washer Toss", description: "" },
  { id: "spike_ball-1", type: "spike_ball", x: 75.2, y: 24.8, name: "Spike Ball", description: "" },
  { id: "pickleball-1", type: "pickleball", x: 47.5, y: 22.7, name: "Pickleball", description: "" },
  { id: "football-1", type: "football", x: 9.7, y: 38.7, name: "Football", description: "" },
  { id: "croquet-1", type: "croquet", x: 66.3, y: 39.5, name: "Croquet", description: "" },
  { id: "bocce_ball-1", type: "bocce_ball", x: 68, y: 24.2, name: "Bocce Ball", description: "" },
  { id: "giant_jenga-1", type: "giant_jenga", x: 66.8, y: 43.9, name: "Giant Jenga", description: "" },
  { id: "can_jam-1", type: "can_jam", x: 66.1, y: 28.9, name: "Can Jam", description: "" },
  { id: "slip_slide-1", type: "slip_slide", x: 36.6, y: 56.1, name: "Slip and Slide", description: "" },
  { id: "the_island-1", type: "the_island", x: 33.9, y: 65, name: "The Island", description: "" },
  { id: "restrooms-mr6q9kvr166", type: "restrooms", x: 75.2, y: 35.3, name: "Restrooms", description: "In the back hallway downstairs" }
];
